// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bibi_protocol.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ConnStatusPacket;
@class ConnStatusPacket_Point;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum NetType

/** 设备类型 */
typedef GPB_ENUM(NetType) {
  NetType_Unknown = 0,
  NetType_Wifi = 1,
  NetType_Wlan2G = 2,
  NetType_Wlan3G = 3,
  NetType_Wlan4G = 4,
  NetType_Unreachable = 5,
};

GPBEnumDescriptor *NetType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NetType_IsValidValue(int32_t value);

#pragma mark - Enum ConnMeta_DeviceType

/** 设备类型 */
typedef GPB_ENUM(ConnMeta_DeviceType) {
  ConnMeta_DeviceType_Unknown = 0,
  ConnMeta_DeviceType_Ios = 1,
  ConnMeta_DeviceType_Android = 2,
};

GPBEnumDescriptor *ConnMeta_DeviceType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ConnMeta_DeviceType_IsValidValue(int32_t value);

#pragma mark - BibiProtocolRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BibiProtocolRoot : GPBRootObject
@end

#pragma mark - ConnMeta

typedef GPB_ENUM(ConnMeta_FieldNumber) {
  ConnMeta_FieldNumber_Uid = 1,
  ConnMeta_FieldNumber_DeviceType = 2,
  ConnMeta_FieldNumber_Version = 3,
  ConnMeta_FieldNumber_DeviceInfo = 4,
  ConnMeta_FieldNumber_SessionId = 5,
  ConnMeta_FieldNumber_ClientFlag = 6,
  ConnMeta_FieldNumber_AuthVersion = 7,
  ConnMeta_FieldNumber_LuaVersion = 8,
  ConnMeta_FieldNumber_ServerPkVersion = 9,
  ConnMeta_FieldNumber_PublicKey = 10,
  ConnMeta_FieldNumber_NetType = 11,
  ConnMeta_FieldNumber_ClientTime = 12,
  ConnMeta_FieldNumber_La = 13,
};

/**
 * 连接的元信息
 **/
@interface ConnMeta : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

@property(nonatomic, readwrite) ConnMeta_DeviceType deviceType;

@property(nonatomic, readwrite) BOOL hasDeviceType;
@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceInfo;
/** Test to see if @c deviceInfo has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

/** 客户端标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientFlag;
/** Test to see if @c clientFlag has been set. */
@property(nonatomic, readwrite) BOOL hasClientFlag;

/** 加密协议 */
@property(nonatomic, readwrite) int32_t authVersion;

@property(nonatomic, readwrite) BOOL hasAuthVersion;
/** lua version */
@property(nonatomic, readwrite) int32_t luaVersion;

@property(nonatomic, readwrite) BOOL hasLuaVersion;
/** server pk version */
@property(nonatomic, readwrite) int32_t serverPkVersion;

@property(nonatomic, readwrite) BOOL hasServerPkVersion;
/** 客户端publickey */
@property(nonatomic, readwrite, copy, null_resettable) NSData *publicKey;
/** Test to see if @c publicKey has been set. */
@property(nonatomic, readwrite) BOOL hasPublicKey;

/** 客户端网络类型 */
@property(nonatomic, readwrite) NetType netType;

@property(nonatomic, readwrite) BOOL hasNetType;
/** 客户端时间 */
@property(nonatomic, readwrite) int64_t clientTime;

@property(nonatomic, readwrite) BOOL hasClientTime;
/** 客户端语言 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *la;
/** Test to see if @c la has been set. */
@property(nonatomic, readwrite) BOOL hasLa;

@end

#pragma mark - ConnStatusPacket

typedef GPB_ENUM(ConnStatusPacket_FieldNumber) {
  ConnStatusPacket_FieldNumber_Code = 1,
  ConnStatusPacket_FieldNumber_ConnToken = 2,
  ConnStatusPacket_FieldNumber_Feedback = 3,
  ConnStatusPacket_FieldNumber_AccessPointsArray = 4,
  ConnStatusPacket_FieldNumber_ClientTime = 5,
};

/**
 * 连接状态包
 **/
@interface ConnStatusPacket : GPBMessage

/** 连接的token */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *connToken;
/** Test to see if @c connToken has been set. */
@property(nonatomic, readwrite) BOOL hasConnToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *feedback;
/** Test to see if @c feedback has been set. */
@property(nonatomic, readwrite) BOOL hasFeedback;

/** 当前可以连接的connectorIP */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ConnStatusPacket_Point*> *accessPointsArray;
/** The number of items in @c accessPointsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger accessPointsArray_Count;

/** 客户端时间 */
@property(nonatomic, readwrite) int64_t clientTime;

@property(nonatomic, readwrite) BOOL hasClientTime;
@end

#pragma mark - ConnStatusPacket_Point

typedef GPB_ENUM(ConnStatusPacket_Point_FieldNumber) {
  ConnStatusPacket_Point_FieldNumber_Hostport = 1,
  ConnStatusPacket_Point_FieldNumber_Weight = 2,
};

/**
 * ap的点
 **/
@interface ConnStatusPacket_Point : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hostport;
/** Test to see if @c hostport has been set. */
@property(nonatomic, readwrite) BOOL hasHostport;

@property(nonatomic, readwrite) int32_t weight;

@property(nonatomic, readwrite) BOOL hasWeight;
@end

#pragma mark - KickPacket

typedef GPB_ENUM(KickPacket_FieldNumber) {
  KickPacket_FieldNumber_Uid = 1,
  KickPacket_FieldNumber_RemoteHostPort = 2,
  KickPacket_FieldNumber_Version = 3,
  KickPacket_FieldNumber_Usession = 4,
  KickPacket_FieldNumber_Csp = 5,
};

/**
 * 踢人
 **/
@interface KickPacket : GPBMessage

/** 被踢人的uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

/** 远端的目标hostport */
@property(nonatomic, readwrite, copy, null_resettable) NSString *remoteHostPort;
/** Test to see if @c remoteHostPort has been set. */
@property(nonatomic, readwrite) BOOL hasRemoteHostPort;

/** 当前的version */
@property(nonatomic, readwrite) int64_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
/** 用户当前的用户态session */
@property(nonatomic, readwrite, copy, null_resettable) NSData *usession;
/** Test to see if @c usession has been set. */
@property(nonatomic, readwrite) BOOL hasUsession;

/** 连接状态包 */
@property(nonatomic, readwrite, strong, null_resettable) ConnStatusPacket *csp;
/** Test to see if @c csp has been set. */
@property(nonatomic, readwrite) BOOL hasCsp;

@end

#pragma mark - Heartbeat

typedef GPB_ENUM(Heartbeat_FieldNumber) {
  Heartbeat_FieldNumber_Timestamp = 1,
  Heartbeat_FieldNumber_Version = 2,
};

/**
 * 心跳包
 **/
@interface Heartbeat : GPBMessage

/** 时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
/** 版本号信息 */
@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@end

#pragma mark - Sync

typedef GPB_ENUM(Sync_FieldNumber) {
  Sync_FieldNumber_Uid = 1,
  Sync_FieldNumber_Version = 2,
};

@interface Sync : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

/** 版本号信息 */
@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@end

#pragma mark - Logout

typedef GPB_ENUM(Logout_FieldNumber) {
  Logout_FieldNumber_Uid = 1,
  Logout_FieldNumber_Version = 2,
};

@interface Logout : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

/** 版本号信息 */
@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
